const test = require('node:test');
const assert = require('node:assert');
const fs = require('fs');
const os = require('os');
const path = require('path');

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'jev-sync-'));
const claudeDir = path.join(tmp, 'claude');
const codexHome = path.join(tmp, 'codex');
process.env.CLAUDE_CONFIG_DIR = claudeDir;
process.env.CODEX_HOME = codexHome;
fs.mkdirSync(path.join(claudeDir, 'plugins'), { recursive: true });
fs.writeFileSync(path.join(claudeDir, 'plugins', 'installed_plugins.json'), '{"plugins":{}}');
fs.writeFileSync(path.join(claudeDir, 'CLAUDE.md'), [
  '# CLAUDE.md',
  '',
  '## Rules',
  '- shared rule',
  '<!-- claude-only:start -->',
  '- claude only rule',
  '<!-- claude-only:end -->',
  '',
  '@RTK.md',
].join('\n'));
fs.writeFileSync(path.join(claudeDir, 'RTK.md'), 'claude rtk body\n');

const sync = require('../plugin/scripts/jev-sync');

test('skips generation when Codex is not installed', () => {
  assert.strictEqual(sync.agentsStatus({ withCaveman: false }), 'no-codex');
  assert.match(sync.syncAgents({ withCaveman: false }), /skipped/);
});

test('generated AGENTS.md: title swapped, claude-only removed, imports inlined', () => {
  fs.mkdirSync(codexHome, { recursive: true });
  const text = sync.buildAgents({ withCaveman: false });
  assert.match(text, /^<!-- Generated by the mynameisjev plugin/);
  assert.match(text, /\n# AGENTS\.md\n\n## Rules/);
  assert.doesNotMatch(text, /claude only rule/);
  assert.match(text, /Prefix every shell command with `rtk`/, 'Claude RTK rules get the prefix rule for Codex');
  assert.match(text, /claude rtk body/);
});

test('a Codex variant of an import wins, and AGENTS.local.md is appended', () => {
  fs.writeFileSync(path.join(codexHome, 'RTK.md'), 'codex rtk body\n');
  fs.writeFileSync(path.join(codexHome, 'AGENTS.local.md'), 'codex only rule\n');
  const text = sync.buildAgents({ withCaveman: false });
  assert.match(text, /codex rtk body/);
  assert.doesNotMatch(text, /claude rtk body/);
  assert.match(text, /codex only rule/);
});

test('caveman block included only when asked, with fallback rules', () => {
  assert.match(sync.buildAgents({ withCaveman: true }), /jev-caveman:start[\s\S]*CAVEMAN MODE ACTIVE[\s\S]*jev-caveman:end/);
  assert.doesNotMatch(sync.buildAgents({ withCaveman: false }), /jev-caveman/);
});

test('sync writes once, keeps a backup of the replaced file', () => {
  fs.writeFileSync(path.join(codexHome, 'AGENTS.md'), 'hand written\n');
  assert.strictEqual(sync.syncAgents({ withCaveman: false }), 'updated');
  assert.strictEqual(sync.syncAgents({ withCaveman: false }), 'unchanged');
  assert.strictEqual(fs.readFileSync(sync.backupPath, 'utf8'), 'hand written\n');
  assert.strictEqual(sync.agentsStatus({ withCaveman: false }), 'in-sync');
});
