#!/usr/bin/env node
// jev-sync — keeps Codex's instructions matched to Claude's. Generates
// ~/.codex/AGENTS.md from ~/.claude/CLAUDE.md, and checks that caveman, RTK
// and the required plugins (jev-plugins.js) are active on both sides.
//
// Generation rules:
// - The "# CLAUDE.md" title becomes "# AGENTS.md".
// - Blocks between <!-- claude-only:start --> and <!-- claude-only:end -->
//   are left out (Claude-specific rules such as the Jev routing rule).
// - `@file` import lines are replaced by the file's contents, because Codex
//   does not expand them. A same-named file in ~/.codex wins over the Claude
//   one, so Codex can have its own variant (its RTK.md tells the agent to
//   prefix commands with `rtk`, which Claude gets from a hook instead).
// - ~/.codex/AGENTS.local.md, if present, is appended for Codex-only rules.
// - The caveman block (jev-caveman.js) goes last, unless caveman is off.

const fs = require('fs');
const path = require('path');
const os = require('os');
const exec = require('./jev-exec');
const caveman = require('./jev-caveman');
const plugins = require('./jev-plugins');

const claudeDir = process.env.CLAUDE_CONFIG_DIR || path.join(os.homedir(), '.claude');
const codexHome = process.env.CODEX_HOME || path.join(os.homedir(), '.codex');
const claudeMdPath = path.join(claudeDir, 'CLAUDE.md');
const agentsPath = path.join(codexHome, 'AGENTS.md');
const localPath = path.join(codexHome, 'AGENTS.local.md');
// One rolling backup: the version before the most recent regeneration.
const backupPath = `${agentsPath}.jev.bak`;

const HEADER = '<!-- Generated by the mynameisjev plugin (/mynameisjev:sync) from ~/.claude/CLAUDE.md. ' +
  'Edit CLAUDE.md, or ~/.codex/AGENTS.local.md for Codex-only rules; edits made here are overwritten. -->';
const RTK_PREFIX_RULE = 'Prefix every shell command with `rtk` (for example `rtk git status`); commands RTK has no filter for run unchanged.';

function readText(file) {
  try {
    return fs.readFileSync(file, 'utf8');
  } catch (e) {
    return null;
  }
}

function resolveImport(ref) {
  if (ref.startsWith('~/')) return path.join(os.homedir(), ref.slice(2));
  return path.isAbsolute(ref) ? ref : path.join(claudeDir, ref);
}

// Contents for an `@ref` import line: the Codex variant if one exists, else
// Claude's file. Returns { text, from } or null when neither exists.
function importContent(ref) {
  const claudeFile = resolveImport(ref);
  const codexFile = path.join(codexHome, path.basename(claudeFile));
  const codexText = readText(codexFile);
  if (codexText !== null) return { text: codexText.trim(), from: codexFile };
  const claudeText = readText(claudeFile);
  if (claudeText === null) return null;
  // Claude's RTK rules assume the Claude hook rewrites commands; Codex has
  // no such hook, so it needs the prefix rule spelled out.
  const text = path.basename(claudeFile) === 'RTK.md' ? `${RTK_PREFIX_RULE}\n\n${claudeText.trim()}` : claudeText.trim();
  return { text, from: claudeFile };
}

const tilde = (p) => p.replace(os.homedir(), '~');

// The AGENTS.md text generated from the current sources, or null when
// CLAUDE.md is missing.
function buildAgents({ withCaveman = true } = {}) {
  const claudeMd = readText(claudeMdPath);
  if (claudeMd === null) return null;

  const body = claudeMd
    .replace(/<!-- claude-only:start[^>]*-->[\s\S]*?<!-- claude-only:end -->\n?/g, '')
    .replace(/^# CLAUDE\.md[ \t]*$/m, '# AGENTS.md')
    .split('\n')
    .map((line) => {
      const m = line.match(/^@(\S+)\s*$/);
      if (!m) return line;
      const inc = importContent(m[1]);
      if (!inc) return `<!-- jev-include: ${m[1]} not found -->`;
      return `<!-- jev-include: ${path.basename(m[1])} (from ${tilde(inc.from)}) -->\n${inc.text}\n<!-- jev-include-end -->`;
    })
    .join('\n')
    .trim();

  const parts = [HEADER, body];
  const local = readText(localPath);
  if (local && local.trim()) parts.push(`<!-- jev-include: AGENTS.local.md -->\n${local.trim()}\n<!-- jev-include-end -->`);
  if (withCaveman) parts.push(caveman.codexBlock());
  return `${parts.join('\n\n')}\n`;
}

// 'in-sync' | 'out-of-sync' | 'no-codex' | 'no-claude-md'
function agentsStatus(opts) {
  if (!fs.existsSync(codexHome)) return 'no-codex';
  const expected = buildAgents(opts);
  if (expected === null) return 'no-claude-md';
  return readText(agentsPath) === expected ? 'in-sync' : 'out-of-sync';
}

// Regenerate AGENTS.md when it differs from the sources. Returns 'updated',
// 'unchanged', or a skip reason.
function syncAgents(opts) {
  if (!fs.existsSync(codexHome)) return 'skipped: Codex not installed';
  const expected = buildAgents(opts);
  if (expected === null) return 'skipped: no CLAUDE.md';
  const current = readText(agentsPath);
  if (current === expected) return 'unchanged';
  if (current !== null) fs.writeFileSync(backupPath, current);
  fs.writeFileSync(agentsPath, expected);
  return 'updated';
}

function rtkBinary() {
  return exec.findOnPath('rtk') !== null;
}

function rtkClaudeHook() {
  try {
    const settings = JSON.parse(fs.readFileSync(path.join(claudeDir, 'settings.json'), 'utf8'));
    return ((settings.hooks && settings.hooks.PreToolUse) || [])
      .some((m) => (m.hooks || []).some((h) => typeof h.command === 'string' && /\brtk hook claude\b/.test(h.command)));
  } catch (e) {
    return false;
  }
}

function rtkCodexRules() {
  return (readText(agentsPath) || '').includes('<!-- jev-include: RTK.md');
}

// { binary, claudeHook, codexRules }
function rtkStatus() {
  return { binary: rtkBinary(), claudeHook: rtkClaudeHook(), codexRules: rtkCodexRules() };
}

// Install RTK's Claude hook when the binary exists but the hook does not.
// The binary itself is not installed here: that is a package-manager choice.
function ensureRtkClaude() {
  if (rtkClaudeHook()) return Promise.resolve('RTK Claude hook: active');
  if (!rtkBinary()) return Promise.resolve('RTK: binary not found on PATH; install RTK first (see its README)');
  return exec.run('rtk', ['init', '-g', '--hook-only', '--auto-patch'], { timeout: 30000 })
    .then(() => 'RTK Claude hook: installed (takes effect in new sessions)')
    .catch((e) => `RTK Claude hook: install failed (${e.message})`);
}

// Everything `/mynameisjev:sync` checks and repairs: caveman, the required plugins
// (jev-plugins.js) on both sides, RTK, and AGENTS.md. Returns report lines.
async function ensureAll({ withCaveman = true } = {}) {
  const lines = [];
  if (withCaveman) {
    try {
      lines.push(`Claude ${await caveman.installClaude()}`);
    } catch (e) {
      lines.push(`Claude caveman: ${e.message}`);
    }
  }
  lines.push(...(await plugins.ensureRequired()));
  lines.push(await ensureRtkClaude());
  try {
    const result = syncAgents({ withCaveman });
    lines.push(`Codex AGENTS.md: ${result === 'updated' ? `regenerated from CLAUDE.md (previous version in ${tilde(backupPath)})` : result}`);
  } catch (e) {
    lines.push(`Codex AGENTS.md: could not write (${e.message})`);
  }
  return lines;
}

module.exports = { buildAgents, agentsStatus, syncAgents, rtkStatus, rtkClaudeHook, ensureAll, agentsPath, backupPath };
